<a href="https://colab.research.google.com/github/saraallan8/Final_Project/blob/main/MusicWave_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Chinook Database Analysis Assignment**

## **Scenario:**

You are a data analyst at **MusicWave Inc.**, a company that specializes in music distribution and sales. Your company uses the Chinook database to manage its music collection, sales, and customer information. Recently, your manager has tasked you with analyzing the database to extract valuable insights that can help the company make informed business decisions.

## **Introduction to the Chinook Database:**

The Chinook database is a sample database that represents a digital media store. It includes tables for:
- **Artists**: Information about the music artists.
- **Albums**: Information about the albums, each linked to an artist.
- **Tracks**: Information about individual tracks, including which album they belong to.
- **Customers**: Information about the customers.
- **Invoices**: Information about sales transactions.
- **InvoiceLines**: Detailed information about each item in an invoice.
- **Genres**: Information about the genres of the tracks.
- **MediaTypes**: Information about the types of media.
- **Employees**: Information about the employees.

The database schema allows for complex queries to analyze various aspects of the music store's operations.

## **Getting Started:**

### **Download the Chinook Database**

1. Download the Chinook SQLite database from [here](https://github.com/lerocha/chinook-database/raw/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite).

2. Upload the `Chinook_Sqlite.sqlite` file to your Google Colab environment.

### **Setting Up the Environment**

Run the following cells to set up your environment and connect to the Chinook database.

```python
# Install sqlite3 library (if not already installed)
!pip install sqlite3

# Import necessary libraries
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('Chinook_Sqlite.sqlite')

In [10]:
!ls

Chinook_Sqlite.sqlite  sample_data

In [11]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('Chinook_Sqlite.sqlite')

# Execute a query
query = "SELECT * FROM sqlite_master where type='table'"

df = pd.read_sql_query(query, conn)
df[['type','name']]

     type           name
0   table          Album
1   table         Artist
2   table       Customer
3   table       Employee
4   table          Genre
5   table        Invoice
6   table    InvoiceLine
7   table      MediaType
8   table       Playlist
9   table  PlaylistTrack
10  table          Track

In [12]:
# Read the first five rows from the Album table
df = pd.read_sql_query("SELECT * FROM album limit 5", conn)

### **Question 1: List All Tables**

**Scenario:**  
Your manager, Alex, is new to the team and is trying to understand the structure of the Chinook database. Alex asks you to provide a list of all the tables in the database to get an overview of the available data.

**Task:**  
Write a query to list all tables in the Chinook database.

In [13]:
df = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)
df

             name
0           Album
1          Artist
2        Customer
3        Employee
4           Genre
5         Invoice
6     InvoiceLine
7       MediaType
8        Playlist
9   PlaylistTrack
10          Track

### **Question 2: Retrieve Top 10 Records from the Albums Table**

**Scenario:**  
Alex wants to familiarize himself with the kind of albums stored in the database. He asks you to fetch a sample of the album records to get a better idea of the data.

**Task:**  
Write a query to retrieve the top 10 records from the Albums table.

---

In [21]:
df = pd.read_sql_query("SELECT * FROM Album ORDER BY AlbumId DESC LIMIT 10 ", conn)
df

   AlbumId                                              Title  ArtistId
0      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275
1      346                              Mozart: Chamber Music       274
2      345                                Monteverdi: L'Orfeo       273
3      344  Schubert: The Late String Quartets & String Qu...       272
4      343                             Respighi:Pines of Rome       226
5      342  Locatelli: Concertos for Violin, Strings and C...       271
6      341  Great Recordings of the Century - Shubert: Sch...       270
7      340        Liszt - 12 Études D'Execution Transcendante       269
8      339  Great Recordings of the Century: Paganini's 24...       268
9      338                        Nielsen: The Six Symphonies       267


### **Question 3: Count the Number of Tracks per Genre**

**Scenario:**  
To plan a marketing campaign, Alex needs to know which genres are most represented in the music store. He asks you to count the number of tracks available for each genre.

**Task:**  
Write a query to count the number of tracks per genre.

---

In [22]:
df = pd.read_sql_query("SELECT Genre.Name, COUNT(Track.TrackId) FROM Genre INNER JOIN Track ON Genre.GenreId = Track.GenreId GROUP BY Genre.Name ", conn)
df

                  Name  COUNT(Track.TrackId)
0          Alternative                    40
1   Alternative & Punk                   332
2                Blues                    81
3           Bossa Nova                    15
4            Classical                    74
5               Comedy                    17
6                Drama                    64
7       Easy Listening                    24
8    Electronica/Dance                    30
9          Heavy Metal                    28
10         Hip Hop/Rap                    35
11                Jazz                   130
12               Latin                   579
13               Metal                   374
14               Opera                     1
15                 Pop                    48
16            R&B/Soul                    61
17              Reggae                    58
18                Rock                  1297
19       Rock And Roll                    12
20    Sci Fi & Fantasy                    26
21     Science Fiction                    13
22          Soundtrack                    43
23            TV Shows                    93
24               World                    28

### **Question 4: Calculate the Total Sales by Country**

**Scenario:**  
Alex is interested in understanding the revenue distribution across different countries. He asks you to calculate the total sales generated from each country.

**Task:**  
Write a query to calculate the total sales by country.

In [23]:
df = pd.read_sql_query("SELECT BillingCountry, SUM(Total) FROM Invoice GROUP BY BillingCountry", conn)
df

    BillingCountry  SUM(Total)
0        Argentina       37.62
1        Australia       37.62
2          Austria       42.62
3          Belgium       37.62
4           Brazil      190.10
5           Canada      303.96
6            Chile       46.62
7   Czech Republic       90.24
8          Denmark       37.62
9          Finland       41.62
10          France      195.10
11         Germany      156.48
12         Hungary       45.62
13           India       75.26
14         Ireland       45.62
15           Italy       37.62
16     Netherlands       40.62
17          Norway       39.62
18          Poland       37.62
19        Portugal       77.24
20           Spain       37.62
21          Sweden       38.62
22             USA      523.06
23  United Kingdom      112.86


### **Question 5: Identify the Top 5 Customers by Total Purchase Amount**

**Scenario:**  
To improve customer relationship management, Alex wants to identify the top spenders. He asks you to find out who the top 5 customers are based on their total purchase amount.

**Task:**  
Write a query to identify the top 5 customers by total purchase amount.

---

In [24]:
df = pd.read_sql_query("SELECT Customer.FirstName,Customer.LastName, SUM(Invoice.Total) AS Total FROM Customer INNER JOIN Invoice ON Customer.CustomerId = Invoice.CustomerId ORDER BY Total DESC LIMIT 5 ", conn)
df

  FirstName LastName   Total
0    Leonie   Köhler  2328.6


### **Question 6: Find the Most Popular Artist by Total Track Sales**

**Scenario:**  
Alex wants to identify the most popular artist in the store based on track sales. He asks you to find out which artist has the highest total track sales.

**Task:**  
Write a query to find the most popular artist by total track sales.

---

In [25]:
df = pd.read_sql_query("SELECT Artist.Name, COUNT(InvoiceLine.InvoiceLineId) AS TotalTrackSales FROM Artist JOIN Album ON Artist.ArtistId = Album.ArtistId JOIN Track ON Album.AlbumId = Track.AlbumId JOIN InvoiceLine ON Track.TrackId = InvoiceLine.TrackId GROUP BY Artist.ArtistId ORDER BY TotalTrackSales DESC LIMIT 1", conn)
df

          Name  TotalTrackSales
0  Iron Maiden              140


### **Question 7: Determine the Average Invoice Total by Customer Country**

**Scenario:**  
To understand the purchasing behavior of customers from different countries, Alex asks you to determine the average invoice total for each country.

**Task:**  
Write a query to determine the average invoice total by customer country.

---

In [26]:
df = pd.read_sql_query("SELECT BillingCountry, AVG(Invoice.Total) AS AvgInvoiceTotal FROM Invoice GROUP BY BillingCountry ", conn)
df

    BillingCountry  AvgInvoiceTotal
0        Argentina         5.374286
1        Australia         5.374286
2          Austria         6.088571
3          Belgium         5.374286
4           Brazil         5.431429
5           Canada         5.427857
6            Chile         6.660000
7   Czech Republic         6.445714
8          Denmark         5.374286
9          Finland         5.945714
10          France         5.574286
11         Germany         5.588571
12         Hungary         6.517143
13           India         5.789231
14         Ireland         6.517143
15           Italy         5.374286
16     Netherlands         5.802857
17          Norway         5.660000
18          Poland         5.374286
19        Portugal         5.517143
20           Spain         5.374286
21          Sweden         5.517143
22             USA         5.747912
23  United Kingdom         5.374286

### **Question 8: Analyze Employee Sales Performance**

**Scenario:**  
Alex wants to evaluate the performance of the sales team. He asks you to analyze the sales performance of each employee.

**Task:**  
Write a query to analyze the sales performance of each employee.

---

In [27]:
df = pd.read_sql_query("SELECT Employee.FirstName, Employee.LastName, COUNT(Invoice.InvoiceId) AS TotalInvoices,SUM(Invoice.Total) AS TotalSales FROM Employee JOIN Customer ON Employee.EmployeeId = Customer.SupportRepId JOIN Invoice ON Customer.CustomerId = Invoice.CustomerId GROUP BY Employee.EmployeeId ORDER BY TotalSales DESC", conn)
df

  FirstName LastName  TotalInvoices  TotalSales
0      Jane  Peacock            146      833.04
1  Margaret     Park            140      775.40
2     Steve  Johnson            126      720.16

### **Question 9: Identify Trends in Monthly Sales**

**Scenario:**  
Alex wants to identify sales trends over time. He asks you to analyze the monthly sales data to spot any trends.

**Task:**  
Write a query to identify trends in monthly sales.

---

In [28]:
df = pd.read_sql_query("SELECT strftime('%Y-%m', InvoiceDate) AS Month, SUM(Total) AS MonthlySales FROM Invoice GROUP BY Month ORDER BY Month", conn)
df

      Month  MonthlySales
0   2021-01         35.64
1   2021-02         37.62
2   2021-03         37.62
3   2021-04         37.62
4   2021-05         37.62
5   2021-06         37.62
6   2021-07         37.62
7   2021-08         37.62
8   2021-09         37.62
9   2021-10         37.62
10  2021-11         37.62
11  2021-12         37.62
12  2022-01         52.62
13  2022-02         46.62
14  2022-03         44.62
15  2022-04         37.62
16  2022-05         37.62
17  2022-06         37.62
18  2022-07         37.62
19  2022-08         37.62
20  2022-09         36.63
21  2022-10         37.62
22  2022-11         37.62
23  2022-12         37.62
24  2023-01         37.62
25  2023-02         37.62
26  2023-03         37.62
27  2023-04         51.62
28  2023-05         42.62
29  2023-06         50.62
30  2023-07         37.62
31  2023-08         37.62
32  2023-09         37.62
33  2023-10         37.62
34  2023-11         23.76
35  2023-12         37.62
36  2024-01         37.62
37  2024-02         37.62
38  2024-03         37.62
39  2024-04         37.62
40  2024-05         37.62
41  2024-06         37.62
42  2024-07         39.62
43  2024-08         47.62
44  2024-09         46.71
45  2024-10         42.62
46  2024-11         37.62
47  2024-12         37.62
48  2025-01         37.62
49  2025-02         27.72
50  2025-03         37.62
51  2025-04         33.66
52  2025-05         37.62
53  2025-06         37.62
54  2025-07         37.62
55  2025-08         37.62
56  2025-09         37.62
57  2025-10         37.62
58  2025-11         49.62
59  2025-12         38.62

### **Question 10: Recommend Marketing Strategies Based on Data Insights**

**Scenario:**  
Based on the insights you have gathered from the previous queries, Alex asks you to recommend at least two marketing strategies that MusicWave Inc. should consider to increase sales and customer satisfaction.

**Task:**  
Based on your analysis, write a brief recommendation for two marketing strategies that could help MusicWave Inc. increase sales and improve customer satisfaction.

In [ ]:
#work more with top artist so this will increase the sales.
#according to the analysis some country the sales in it more than another so i suggest to do more marketing in the lowest country sales to make the musicwave best known for increasing sales